# Site settings
title: 会敲代码的熊
description: 会敲代码的熊
favicon: /assets/img/avatar.JPG
baseurl: https://mm12432.github.io/
url: https://mm12432.github.io/
#rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: 毛晓勇
  title: 用心甘情愿的态度 过随遇而安的生活
  address: 秦皇岛，中国
  email: mm12432@163.com
  link: https://mm12432.github.io/
  gavatar: /assets/img/avatar.JPG
#  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: 山海关船舶重工有限责任公司-信息中心
      location: 秦皇岛，中国
      title: 高级程序员
      started: 2014
      duration: (2014 - 今)
      description: 带领过4人开发团队，为公司开发过几个中小型的企业管理系统和软件，不过成长过后也曾彷徨，但最终还是找到了一个向往的发展方向--数据分析/数据挖掘，在看过斯坦福吴恩达教授的机器学习公开课之后，我便彻底的爱上了机器学习这门艺术，经过大数据分析与云计算的培训（hadoop生态，spark，storm，openstack）后，更是加强了我对分布式计算的认识，以及加深了数据挖掘前沿工具的了解及应用水平的提高，随着人工智能的兴起，数据分析/数据挖掘必将在未来的IT领域中大放异彩。
    - work2:
      company: 山海关船舶重工有限责任公司-信息中心
      location: 秦皇岛，中国
      title: 程序员
      started: 2011
      duration: (2011 - 2014)
      description: 在这个阶段里，我用不断的自学和小项目来充实我的知识库，先后学会了面向对象编程方法，及C#高级特性（反射，委托，泛型，集合等），winform，wpf，水晶报表，web service，asp.net，html+css+js，mvc，orm，依赖注入，单元测试，数据库设计及实现，sql server，数据结构及算法，面向对象设计模式，重构方法，软件工程，scrum敏捷开发方法，企业架构模式，团队开发（微软tfs）等众多知识点，并能把学到的知识应用到实际的企业开发中去，至此成长与蜕变完成。
    - work3:
      company: 山海关船舶重工有限责任公司-设计所
      location: 秦皇岛，中国
      title: 助理设计师
      started: 2008
      duration: (2008 - 2011)
      description: 一段自我重塑的经历，参加过公司3艘散货船的生产设计工作；参与过2次船舶的倾斜实验，并撰写实验报告；1年后因不喜爱船舶设计工作转入计算机室，从事过1年的系统维护和网络维护工作，然后自学Java和C#语言，写过一些常用的小程序帮助其他同事解决简单的问题。
  educationHistory:
    - education1:
      organization: 哈尔滨工程大学
      location: 哈尔滨，中国
      degree: 工学学士
      major: 船舶与海洋工程
      started: 2004
      duration: (2004 - 2008)
      description: 本该选择计算机科学与技术专业的我，鬼使神差的选择了船舶与海洋工程。心之所向，身之所往，经过几年的努力，我又回到了我向往的那个起点，开始一段♥的征程。
  languages:
    - language1:
      name: 汉语
      proficiency: 母语
    - language2:
      name: 英语
      proficiency: 一般
  programmingSkills:
    - skill1:
      name: .net Framework
      percentage: 100%
    - skill2:
      name: asp.net
      percentage: 90%
    - skill3:
      name: hadoop
      percentage: 70%
    - skill4:
      name: data mining
      percentage: 50%
    - skill5:
      name: spark
      percentage: 50%
  location:
      east: 119.8294753533
      north: 39.9882562369
